# -*- coding: utf-8 -*-
"""Monthly Sales Analysis and Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2O9q8eTxa0aDRlrDBzYI2KOTiuVYxD9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

"""**Step 1: Load Dataset**"""

df= pd.read_csv("/sales_data_clean.csv")

df.head()

df.info()

"""**Step 2: Data Cleaning & Preprocessing**"""

df.isnull().sum()

"""**Step 3: Calculate Total Sales per Month**"""

df.fillna(0, inplace=True)

df.columns

df['Total_Sales'] = df[['Product_A','Product_B','Product_C']].sum(axis=1)
print(df[['Month','Total_Sales']])

"""**Step 4: Average Sales per Product**"""

avg_sale = df[['Product_A', 'Product_B' ,'Product_C']].mean()
print("Average Sales per Product : \n" , avg_sale)

"""**Step 5: Identify Peak and Lowest Sales Months**"""

max_month = df.loc[df['Total_Sales'].idxmax(), 'Month']
min_month = df.loc[df['Total_Sales'].idxmin(), 'Month']

print(f"Month with highest sales: {max_month}")
print(f"Month with lowest sales: {min_month}")

"""**Step 6: Basic Forecasting for Next Month**"""

forecast = {}
for product in ['Product_A','Product_B','Product_C']:
    # Calculate average growth rate per month
    growth_rate = np.mean(np.diff(df[product]))
    forecast[product] = int(df[product].iloc[-1] + growth_rate)

# Forecast total sales
forecast['Total_Sales'] = sum(forecast.values())
print("Next Month Sales Forecast:", forecast)

"""**Step 7: Month-over-Month Growth %**"""

for product in ['Product_A','Product_B','Product_C']:
  df[product + '_Growth%']=df[product].pct_change() *100

print(df)

"""**Step 8: Visualization of Sales Trends**"""

df.plot(x='Month' , y=['Product_A' ,'Product_B' ,'Product_C'] , marker='o')
plt.title("Monthly Sales Trends")
plt.xlabel("Month")
plt.ylabel("Units Sold")
plt.xticks(rotation=45) # name position
plt.grid(True)
plt.show()

"""**Step 9: Correlation Analysis (Optional)**"""

correlation = df[['Product_A','Product_B','Product_C']].corr()
print("Correlation between products:\n", correlation)

"""**Step 10: Save Processed Dataset**"""

df.to_csv('/kaggle/processed_sales_data.csv', index=False)
print("Processed CSV saved as 'processed_sales_data.csv'")

"""**Step 11: Optional Advanced Analysis**

Top 3 months for each product
"""

for product in ['Product_A','Product_B','Product_C']:
    top_months = df.nlargest(3, product)[['Month', product]]
    print(f"Top 3 months for {product}:\n", top_months, "\n")

